export default () => {
  return async (ctx, next) => {
    const [user] = await strapi.entityService.findMany('plugin::users-permissions.user',{
      filters:{
        player_match_position: ctx.request.params.playerMatchPosition
      },
      populate: 'teams'
    })
    if(user){
      ctx.state.autogeneratedUserInstance = user
      return next()
    }else{
      ctx.status = 400
      ctx.message = 'No user instance found. The user may already be assigned.'
    } 
  };
};
